# Generated by Django 5.0.1 on 2024-03-10 07:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('global_id', models.CharField(max_length=300, null=True, unique=True)),
                ('host', models.URLField(default='', max_length=300)),
                ('source', models.URLField(default='', max_length=300)),
                ('origin', models.URLField(default='', max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('contentType', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('FRIENDS', 'FRIENDS'), ('UNLISTED', 'UNLISTED')], default='PUBLIC', max_length=8)),
            ],
        ),
    ]
