# Generated by Django 5.0.2 on 2024-02-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_author_alter_post_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='global_id',
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
    ]
