# Generated by Django 5.0.1 on 2024-04-07 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='host',
        ),
    ]
