# Generated by Django 5.0.1 on 2024-03-20 17:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0002_initial'),
        ('followers', '0001_initial'),
        ('likes', '0001_initial'),
        ('posts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('global_id', models.CharField(max_length=300, unique=True)),
                ('type', models.URLField(default='', max_length=300)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comment', models.ManyToManyField(blank=True, to='comments.comment')),
                ('follow', models.ManyToManyField(blank=True, to='followers.newfollowrequest')),
                ('like', models.ManyToManyField(blank=True, to='likes.postlike')),
                ('post', models.ManyToManyField(blank=True, to='posts.post')),
            ],
        ),
    ]
