# Generated by Django 5.0.1 on 2024-03-27 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0002_followstatus_delete_follower_delete_friends_and_more'),
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='followRequest',
            field=models.ManyToManyField(blank=True, to='followers.followstatus'),
        ),
    ]
