# Generated by Django 5.0.1 on 2024-03-20 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='global_id',
        ),
    ]
