# Generated by Django 5.0.1 on 2024-04-06 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='commentLikes',
        ),
    ]
