# Generated by Django 5.0.1 on 2024-03-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0003_alter_inbox_author'),
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inbox',
            old_name='like',
            new_name='postLikes',
        ),
        migrations.AddField(
            model_name='inbox',
            name='commentLikes',
            field=models.ManyToManyField(blank=True, to='likes.commentlike'),
        ),
    ]
