# Generated by Django 5.0.1 on 2024-03-22 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0004_rename_like_inbox_postlikes_inbox_commentlikes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inbox',
            old_name='follow',
            new_name='followRequest',
        ),
    ]
