# Generated by Django 5.0.1 on 2024-03-26 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='global_id',
        ),
    ]
