version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    network_mode: "host"
    volumes:
      - /usr/src/backend/sql:/usr/src/backend/sql
    restart: always
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    network_mode: "host"
    restart: always    