version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    pull_policy: build
    network_mode: "host"
    volumes:
      - ./:/usr/src/backend/database
      - ./:/usr/src/backend/media
    restart: always
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    pull_policy: build
    network_mode: "host"
    restart: always    