# Generated by Django 5.0.1 on 2024-03-26 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='global_id',
        ),
    ]
