# Generated by Django 5.0.1 on 2024-03-17 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='global_id',
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
    ]
