# Generated by Django 5.0.2 on 2024-02-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='host',
            field=models.URLField(default='', max_length=300),
        ),
    ]
