# Generated by Django 5.0.1 on 2024-03-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.TextField(default='', editable=False)),
                ('followerId', models.TextField(default='', editable=False)),
                ('host', models.TextField(blank=True, default='')),
                ('displayName', models.TextField(blank=True, default='')),
                ('url', models.TextField(blank=True, default='')),
                ('github', models.TextField(blank=True, default='')),
                ('profileImage', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.TextField(default='', editable=False)),
                ('friendId', models.TextField(default='', editable=False)),
                ('host', models.TextField(blank=True, default='')),
                ('displayName', models.TextField(blank=True, default='')),
                ('url', models.TextField(blank=True, default='')),
                ('github', models.TextField(blank=True, default='')),
                ('profileImage', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='NewFollowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.TextField(default='', editable=False)),
                ('followerId', models.TextField(default='', editable=False)),
                ('host', models.TextField(blank=True, default='')),
                ('displayName', models.TextField(blank=True, default='')),
                ('url', models.TextField(blank=True, default='')),
                ('github', models.TextField(blank=True, default='')),
                ('profileImage', models.TextField(blank=True, default='')),
            ],
        ),
    ]
