# Generated by Django 5.0.1 on 2024-03-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('follower', models.CharField(max_length=100)),
                ('followerUrl', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='NewFollowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('follower', models.CharField(max_length=100)),
                ('followerUrl', models.CharField(max_length=300)),
            ],
        ),
    ]
