# Generated by Django 5.0.1 on 2024-03-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='follower',
            name='followerUrl',
        ),
        migrations.RemoveField(
            model_name='follower',
            name='name',
        ),
        migrations.RemoveField(
            model_name='newfollowrequest',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='newfollowrequest',
            name='followerUrl',
        ),
        migrations.RemoveField(
            model_name='newfollowrequest',
            name='name',
        ),
        migrations.AddField(
            model_name='follower',
            name='displayName',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='follower',
            name='github',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='follower',
            name='host',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='follower',
            name='profileImage',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='follower',
            name='url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='newfollowrequest',
            name='displayName',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='newfollowrequest',
            name='github',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='newfollowrequest',
            name='host',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='newfollowrequest',
            name='profileImage',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='newfollowrequest',
            name='url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='follower',
            name='id',
            field=models.TextField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='newfollowrequest',
            name='id',
            field=models.TextField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
