# Generated by Django 5.0.1 on 2024-02-25 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0002_rename_followers_follower_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='url',
            new_name='followerUrl',
        ),
        migrations.RenameField(
            model_name='newfollowrequest',
            old_name='url',
            new_name='followerUrl',
        ),
    ]
