# Generated by Django 5.0.1 on 2024-03-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0002_remove_follower_follower_remove_follower_followerurl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='followerId',
            field=models.TextField(default=None, editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newfollowrequest',
            name='followerId',
            field=models.TextField(default=None, editable=False, unique=True),
            preserve_default=False,
        ),
    ]
