# Generated by Django 5.0.1 on 2024-03-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0003_follower_followerid_newfollowrequest_followerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.TextField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('friendId', models.TextField(editable=False, unique=True)),
                ('host', models.TextField(blank=True, default='')),
                ('displayName', models.TextField(blank=True, default='')),
                ('url', models.TextField(blank=True, default='')),
                ('github', models.TextField(blank=True, default='')),
                ('profileImage', models.TextField(blank=True, default='')),
            ],
        ),
    ]
