# Generated by Django 5.0.1 on 2024-03-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0004_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='followerId',
        ),
        migrations.RemoveField(
            model_name='newfollowrequest',
            name='followerId',
        ),
        migrations.AddField(
            model_name='follower',
            name='friendId',
            field=models.TextField(default='', editable=False),
        ),
        migrations.AddField(
            model_name='follower',
            name='userId',
            field=models.TextField(default='', editable=False),
        ),
        migrations.AddField(
            model_name='friends',
            name='userId',
            field=models.TextField(default='', editable=False),
        ),
        migrations.AddField(
            model_name='newfollowrequest',
            name='friendId',
            field=models.TextField(default='', editable=False),
        ),
        migrations.AddField(
            model_name='newfollowrequest',
            name='userId',
            field=models.TextField(default='', editable=False),
        ),
        migrations.AlterField(
            model_name='follower',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='friends',
            name='friendId',
            field=models.TextField(default='', editable=False),
        ),
        migrations.AlterField(
            model_name='friends',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='newfollowrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
