# Generated by Django 5.0.1 on 2024-03-22 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0005_remove_follower_followerid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='friendId',
            new_name='followerId',
        ),
        migrations.RenameField(
            model_name='newfollowrequest',
            old_name='friendId',
            new_name='followerId',
        ),
    ]
