# Generated by Django 5.0.1 on 2024-02-25 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Followers',
            new_name='Follower',
        ),
        migrations.RenameModel(
            old_name='NewFollowRequests',
            new_name='NewFollowRequest',
        ),
    ]
