# Generated by Django 5.0.1 on 2024-02-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0003_rename_url_follower_followerurl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='id',
        ),
        migrations.RemoveField(
            model_name='newfollowrequest',
            name='id',
        ),
        migrations.AlterField(
            model_name='follower',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='newfollowrequest',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
