# Generated by Django 5.0.1 on 2024-02-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0004_remove_follower_id_remove_newfollowrequest_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='follower',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='follower',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='newfollowrequest',
            name='follower',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='newfollowrequest',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
