# Generated by Django 5.0.2 on 2024-02-27 00:13

import django.utils.timezone
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_followers_alter_user_displayname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='profileBackgroundImage',
            field=models.ImageField(null=True, upload_to=users.models.profilebackground_upload_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='profileImage',
            field=models.ImageField(null=True, upload_to=users.models.pfp_upload_path),
        ),
    ]
