# Generated by Django 5.0.2 on 2024-02-27 05:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='global_id',
            field=models.CharField(default=1, max_length=300, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
