# Generated by Django 5.0.2 on 2024-02-27 06:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_global_id_user_url_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='host',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='global_id',
            field=models.CharField(default=uuid.uuid4, max_length=300, unique=True),
        ),
    ]
