# Generated by Django 5.0.1 on 2024-03-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='username',
            field=models.CharField(default='User', max_length=50),
            preserve_default=False,
        ),
    ]
