# Generated by Django 5.0.1 on 2024-03-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_node_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='is_self',
            field=models.BooleanField(default=False),
        ),
    ]
