# Generated by Django 5.0.1 on 2024-03-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0003_node_is_self'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='url',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
